// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfBtqEx_lv64i9E1NkgENr7kB16FiXGyI',
    appId: '1:362634025268:web:8f4f9b94da43bcfe6aed61',
    messagingSenderId: '362634025268',
    projectId: 'agrinexus-ffc04',
    authDomain: 'agrinexus-ffc04.firebaseapp.com',
    storageBucket: 'agrinexus-ffc04.firebasestorage.app',
    measurementId: 'G-4Z3XH4X6PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbBlazXjJmx4ZVertrA1EOvWv6lbvreIU',
    appId: '1:362634025268:android:e6f7cc758a7405b76aed61',
    messagingSenderId: '362634025268',
    projectId: 'agrinexus-ffc04',
    storageBucket: 'agrinexus-ffc04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLAOrKk_k64XhhVs_t3Mg2yqhyIPPr5e8',
    appId: '1:362634025268:ios:64532bd43d05b1816aed61',
    messagingSenderId: '362634025268',
    projectId: 'agrinexus-ffc04',
    storageBucket: 'agrinexus-ffc04.firebasestorage.app',
    iosBundleId: 'com.example.agrinexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLAOrKk_k64XhhVs_t3Mg2yqhyIPPr5e8',
    appId: '1:362634025268:ios:64532bd43d05b1816aed61',
    messagingSenderId: '362634025268',
    projectId: 'agrinexus-ffc04',
    storageBucket: 'agrinexus-ffc04.firebasestorage.app',
    iosBundleId: 'com.example.agrinexus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfBtqEx_lv64i9E1NkgENr7kB16FiXGyI',
    appId: '1:362634025268:web:1c35a8070d72c4176aed61',
    messagingSenderId: '362634025268',
    projectId: 'agrinexus-ffc04',
    authDomain: 'agrinexus-ffc04.firebaseapp.com',
    storageBucket: 'agrinexus-ffc04.firebasestorage.app',
    measurementId: 'G-XQCQ3NEZZN',
  );
}
